In [3]:
import numpy as np
import torch        

In [9]:
np_array = np.array([65,567])
print(np_array.dtype)
print(type(np_array))

int64
<class 'numpy.ndarray'>


In [7]:
tr_array = torch.tensor([])
print(tr_array.dtype)
print(type(tr_array))


torch.float32
<class 'torch.Tensor'>


In [13]:
tr_2 = torch.tensor(np_array)
print(tr_2)
print(np_array)


tensor([ 65, 567])
[ 65 567]


If we use "from_numpy" function to convert a numpy array to torch tensor then it will copy the array address instead of vlaue as a result it will help  us to generate a tensor without regenerate the copy of an array rather use the previous array and casting it by using reference value of it.

In [15]:
a = np.array([21,22,23])
b = torch.from_numpy(a)
b[2] = 3333
print(a,'\n',b)

[  21   22 3333] 
 tensor([  21,   22, 3333])
